"""Build this sketch's two header views of the frozen output vocabulary.

Cloned from firmware/esp32_barista/tools/generate_vocab_headers.py: same
contract, KNOTS_* naming and knots' own EXPECTED_WORDS instead of barista's.

Writes generated/knots_words.h (class id -> displayed word) and
generated/knots_out2in.h (class id -> input token id). Both are firmware
views of the same vocabulary contract.

This script CONSUMES the frozen vocabulary; it does not derive it. The write
vocabulary was assembled by research/knots/build_word_list.py (knot names
plus a hand-authored supplement) and research/knots/build_vocab.py (out2in,
against the trained tokenizer). That assembly is a separate process which is
not performed here: once a model exists the pair is frozen, because changing
either one invalidates the trained head. So this script only validates the
pair and formats it for the compiler.

Like barista, knots' head is untied: it reads a BPE vocabulary and writes
only the curated words in vocab.json. Sampling therefore produces a CLASS
index, and that class has to be mapped back to an input token id before it
can be fed forward. layout.json holds that map.

Every check below guards a failure that is silent on device. Note what out2in
does NOT control: the word printed for a class comes from knots_words.h, so a
wrong entry still prints the right word. What it corrupts is the token fed into
the NEXT decoding step. The visible damage therefore appears after the mistake,
in the rest of the answer, which is far harder to trace than a crash.

Not verified here: the classes that reuse an existing BPE id cannot be
checked from these two files alone. Confirming that such a class maps to the id
which actually encodes its own word needs tokenizer.json, and belongs to the
integration gate rather than to this conversion.

Both headers are a pure function of the two JSON inputs. No timestamp, no host
state, so regenerating on any machine produces byte-identical output.

  uv run python firmware/esp32_knots/tools/generate_vocab_headers.py
"""

import argparse
import json
from pathlib import Path
from typing import Any

SKETCH = Path(__file__).resolve().parent.parent
ROOT = SKETCH.parent.parent
DEFAULT_VOCAB = ROOT / "artifacts" / "knots" / "vocab.json"
DEFAULT_LAYOUT = ROOT / "artifacts" / "knots" / "layout.json"
DEFAULT_OUT_DIR = SKETCH / "generated"

# The current knots output vocabulary is frozen at this many rows: the
# trained head has exactly that many and the sketch refuses a model whose
# out_vocab disagrees. Growing it is a vocabulary version bump, not a silent
# regeneration, so a different count here means the wrong file was passed
# rather than that this constant is stale. Bump alongside output_words.json.
EXPECTED_WORDS = 284

# Class ids 0..3, in this order. The emitted KNOTS_* constants are indices
# into this tuple, so the header and this check cannot drift apart.
SPECIALS = ("<pad>", "<bos>", "<eos>", "<unk>")

WORDS_PER_LINE = 8
IDS_PER_LINE = 16
BANNER = "// Generated by firmware/esp32_knots/tools/generate_vocab_headers.py"


def is_int(value: Any) -> bool:
    """A JSON integer, excluding bool.

    bool is a subclass of int in Python, so True would satisfy every range and
    arithmetic check below and then emit `True` into a uint16_t array.
    """
    return isinstance(value, int) and not isinstance(value, bool)


def const_name(token: str) -> str:
    """Name the C constant for a special token: <pad> becomes KNOTS_PAD."""
    return "KNOTS_" + token.strip("<>").upper()


def c_string(word: str) -> str:
    """Quote one word as a C string literal.

    The device Serial.print()s these bytes straight out and its encoder is ASCII
    only, so anything outside printable ASCII is a corpus error rather than
    something to escape and pass on. Backslash and quote are escaped because a
    vocabulary is data: it must not be able to terminate the literal.
    """
    for ch in word:
        if not 0x20 <= ord(ch) <= 0x7E:
            raise SystemExit(
                f"word {word!r} contains a character outside printable ASCII; the device encoder cannot represent it"
            )
    return '"' + word.replace("\\", "\\\\").replace('"', '\\"') + '"'


def read_json(path: str | Path, what: str) -> dict:
    """Read one canonical input, or say which one is missing and where.

    The defaults live under artifacts/, which is ignored and therefore absent in
    a fresh clone. A bare FileNotFoundError names a path but not what was
    expected there, which is the wrong half of the answer.
    """
    path = Path(path)
    if not path.is_file():
        raise SystemExit(
            f"{what} not found: {path}\n"
            f"knots' canonical assets belong in {DEFAULT_VOCAB.parent}; "
            f"pass --vocab and --layout if yours are elsewhere."
        )
    return json.loads(path.read_text())


def load(vocab_path: str | Path, layout_path: str | Path) -> tuple[list[str], list[int], dict]:
    """Read and validate both inputs. Returns (words, out2in, layout)."""
    vocab = read_json(vocab_path, "output vocabulary")
    layout = read_json(layout_path, "layout")

    words = [entry["token"] for entry in vocab["tokens"]]
    out2in = layout["out2in"]

    # Types before arithmetic. Every size and range check below is meaningless
    # on a value that is not an integer: a float passes them and is then
    # truncated by the C compiler, and a bool passes them as 0 or 1.
    for field in ("bpe_vocab", "total", "n_words"):
        if not is_int(layout[field]):
            raise SystemExit(f"layout {field} must be an integer, found {layout[field]!r}")
    if not is_int(vocab["total"]):
        raise SystemExit(f"output vocabulary total must be an integer, found {vocab['total']!r}")
    non_integer = [(k, v) for k, v in enumerate(out2in) if not is_int(v)]
    if non_integer:
        k, token_id = non_integer[0]
        raise SystemExit(
            f"out2in class {k} is {token_id!r}, which is not an integer "
            f"({len(non_integer)} in total); C converts such a value into "
            f"uint16_t and the result can collide with another class"
        )

    bpe_vocab, total, n_words = layout["bpe_vocab"], layout["total"], layout["n_words"]

    if len(words) != EXPECTED_WORDS:
        raise SystemExit(f"output vocabulary has {len(words)} tokens, expected {EXPECTED_WORDS}")
    # The count is stated twice in vocab.json. If the two disagree, the file has
    # been edited by hand and neither number can be trusted.
    if vocab["total"] != len(words):
        raise SystemExit(
            f"output vocabulary is self-contradictory: total={vocab['total']} but it lists {len(words)} tokens"
        )
    if len(set(words)) != len(words):
        seen, dup = set(), []
        for k, word in enumerate(words):
            if word in seen:
                dup.append((k, word))
            seen.add(word)
        raise SystemExit(
            f"output vocabulary class {dup[0][0]} repeats the word "
            f"{dup[0][1]!r} ({len(dup)} duplicates in total); the two classes "
            f"print identically but carry different next-step state, so which "
            f"one the head chose is invisible in the answer"
        )
    if not n_words == len(words) == len(out2in):
        raise SystemExit(
            f"size disagreement: layout n_words={n_words}, vocab tokens={len(words)}, out2in={len(out2in)}"
        )
    if tuple(words[: len(SPECIALS)]) != SPECIALS:
        raise SystemExit(f"class ids 0..{len(SPECIALS) - 1} must be {list(SPECIALS)}, found {words[: len(SPECIALS)]}")

    if len(set(out2in)) != len(out2in):
        seen, dup = set(), []
        for k, token_id in enumerate(out2in):
            if token_id in seen:
                dup.append((k, token_id))
            seen.add(token_id)
        raise SystemExit(
            f"out2in class {dup[0][0]} reuses input id {dup[0][1]}, already "
            f"taken by an earlier class ({len(dup)} duplicates in total); the "
            f"two classes print different words but collapse onto one "
            f"next-step state"
        )
    out_of_range = [(k, v) for k, v in enumerate(out2in) if not 0 <= v < total]
    if out_of_range:
        k, token_id = out_of_range[0]
        raise SystemExit(f"out2in class {k} is {token_id}, outside [0,{total}) ({len(out_of_range)} in total)")

    new_rows = sum(1 for token_id in out2in if token_id >= bpe_vocab)
    if bpe_vocab + new_rows != total:
        raise SystemExit(
            f"layout does not add up: bpe_vocab {bpe_vocab} + {new_rows} new "
            f"rows = {bpe_vocab + new_rows}, but total is {total}"
        )
    # Appended rows are allocated in class order when the vocabulary is frozen,
    # so the subsequence of ids at or above bpe_vocab must be exactly
    # range(bpe_vocab, total). Nothing above catches a swap within it: both ids
    # stay unique, both stay in range, and the totals still agree. Lengths are
    # equal here because the sum check above already passed.
    appended = [token_id for token_id in out2in if token_id >= bpe_vocab]
    expected = list(range(bpe_vocab, total))
    if appended != expected:
        first = next(i for i, (a, b) in enumerate(zip(appended, expected)) if a != b)
        raise SystemExit(
            f"appended out2in ids are not in class order: appended position "
            f"{first} is {appended[first]}, expected {expected[first]}"
        )

    # KNOTS_OUT2IN is uint16_t, which is the whole point of the table being
    # small. A larger read vocabulary needs a wider element type, not a cast.
    if total > 0x10000:
        raise SystemExit(f"read vocabulary {total} does not fit uint16_t")

    return words, out2in, layout


def render_words(words: list[str]) -> str:
    """Render generated/knots_words.h: class id -> word, plus the SPECIALS #defines."""
    lines = [
        BANNER,
        "// output vocabulary, class id -> text. The model writes only these.",
        "#ifndef KNOTS_WORDS_H",
        "#define KNOTS_WORDS_H",
        "",
        f"#define KNOTS_WORD_COUNT {len(words)}",
        "",
        f"static const char *const KNOTS_WORDS[{len(words)}] = {{",
    ]
    for i in range(0, len(words), WORDS_PER_LINE):
        chunk = words[i : i + WORDS_PER_LINE]
        lines.append("  " + " ".join(c_string(w) + "," for w in chunk))
    lines += ["};", ""]
    lines += [f"#define {const_name(t)} {i}" for i, t in enumerate(SPECIALS)]
    lines += ["", "#endif"]
    return "\n".join(lines) + "\n"


def render_out2in(out2in: list[int], reused: int) -> str:
    """Render generated/knots_out2in.h: class id -> input token id."""
    lines = [
        BANNER,
        "// output class k -> input token id. Not a uniform offset:",
        f"// {reused} writable words already existed as BPE tokens and keep their ids.",
        "#ifndef KNOTS_OUT2IN_H",
        "#define KNOTS_OUT2IN_H",
        "#include <stdint.h>",
        "",
        f"static const uint16_t KNOTS_OUT2IN[{len(out2in)}] = {{",
    ]
    for i in range(0, len(out2in), IDS_PER_LINE):
        chunk = out2in[i : i + IDS_PER_LINE]
        lines.append("  " + " ".join(f"{token_id}," for token_id in chunk))
    lines += ["};", "", "#endif"]
    return "\n".join(lines) + "\n"


def generate(vocab_path: str | Path, layout_path: str | Path, out_dir: str | Path) -> tuple[Path, Path]:
    """Validate the inputs and write both headers. Returns the two paths."""
    words, out2in, layout = load(vocab_path, layout_path)
    reused = sum(1 for token_id in out2in if token_id < layout["bpe_vocab"])

    out_dir = Path(out_dir)
    # Generated headers are ignored, so the directory is absent in a fresh clone.
    out_dir.mkdir(parents=True, exist_ok=True)
    words_h = out_dir / "knots_words.h"
    out2in_h = out_dir / "knots_out2in.h"
    words_h.write_text(render_words(words))
    out2in_h.write_text(render_out2in(out2in, reused))

    print(f"wrote {words_h}: {len(words)} words")
    print(
        f"wrote {out2in_h}: {len(out2in)} ids, {reused} reuse an existing BPE "
        f"id, {len(out2in) - reused} new rows, read vocabulary "
        f"{layout['bpe_vocab']} -> {layout['total']}"
    )
    return words_h, out2in_h


def main() -> None:
    """Parse --vocab/--layout/--out-dir, then generate both headers."""
    ap = argparse.ArgumentParser(
        description="Generate the knots word tables from the frozen output vocabulary and its input-id layout."
    )
    ap.add_argument("--vocab", default=DEFAULT_VOCAB, help="canonical output vocabulary vocab.json")
    ap.add_argument("--layout", default=DEFAULT_LAYOUT, help="canonical layout.json, holds out2in")
    ap.add_argument("--out-dir", default=DEFAULT_OUT_DIR, help="directory both headers are written to")
    args = ap.parse_args()
    generate(args.vocab, args.layout, args.out_dir)


if __name__ == "__main__":
    main()
