"""Pack this sketch's BPE encoder tables into a C header.

Cloned from firmware/esp32_barista/tools/generate_tokenizer_header.py --
identical BTK1 format and logic, only DEFAULT_TOKENIZER differs.

Writes generated/tokenizer_encoder.h: the BTK1 asset that runtime/bpe_tokenizer.h
loads, as a PROGMEM byte array. Like barista, knots reads free-form typed
questions, so unlike TinyStories it needs an encoder on device, not just a
decode table.

This script consumes the frozen tokenizer.json; it does not train it.

BTK1 layout, all little endian:

  offset  size  field
       0     4  magic "BTK1"
       4     4  format version (2)
       8     4  active vocabulary size
      12     4  merge count
      16     4  reserved, stored as zero
      20     4  merge base, the token id of merge rank 0
      24    28  sha256 of tokenizer.json, truncated. Provenance only; the
                runtime never reads it.
      52   512  256 uint16 byte token ids, indexed by raw byte
     564   6*n  merge entries: uint32 key (left << 16 | right), uint16 rank,
                sorted ascending by key

Offset 16 is reserved. It is not an end-of-sequence id: like barista, knots'
end of answer is output class 2 in the word tables (KNOTS_EOS), a value that
lives in knots_words.h, not in this asset. The encoder does not use this field.

Invariants this script enforces, each because the runtime depends on it:

  - vocabulary ids are the dense range 0..active_vocab-1. The asset stores only
    a count, and merge results are derived from rank plus base, so a gap or a
    repeat makes both meaningless.
  - merge entries are sorted by key, because btk_merge_rank binary searches
    them. An unsorted table does not fail, it silently stops finding merges.
  - the configuration is the one the device implements: ByteLevel
    pre-tokenization over a plain BPE model, nothing else. Any other setting
    would tokenize differently on device than in Python.

  uv run python firmware/esp32_knots/tools/generate_tokenizer_header.py
"""

import argparse
import hashlib
import json
import struct
from pathlib import Path
from typing import Any

SKETCH = Path(__file__).resolve().parent.parent
ROOT = SKETCH.parent.parent
DEFAULT_TOKENIZER = ROOT / "artifacts" / "knots" / "tokenizer.json"
DEFAULT_OUT = SKETCH / "generated" / "tokenizer_encoder.h"

MAGIC = b"BTK1"
FORMAT_VERSION = 2
HEADER_STRUCT = "<4sIIIII28s"  # 52 bytes, see the layout above
RESERVED = 0
UINT16_LIMIT = 0x10000
BYTES_PER_LINE = 20
BANNER = "// Generated by firmware/esp32_knots/tools/generate_tokenizer_header.py"

# Settings the device encoder does not implement. Present and non-null means the
# Python tokenizer would do something the device cannot, so the asset would
# encode text differently from the corpus the model was trained on.
TOP_LEVEL_ABSENT = ("truncation", "padding", "normalizer", "post_processor")
PRE_TOKENIZER_REQUIRED = {"add_prefix_space": False, "use_regex": True}
MODEL_DISABLED = {
    "dropout": (None, 0, 0.0),
    "unk_token": (None, ""),
    "continuing_subword_prefix": (None, ""),
    "end_of_word_suffix": (None, ""),
    "byte_fallback": (None, False),
    "ignore_merges": (None, False),
}


def is_int(value: Any) -> bool:
    """A JSON integer, excluding bool.

    bool is a subclass of int in Python, so True would pass every range check
    below and then be packed as the id 1.
    """
    return isinstance(value, int) and not isinstance(value, bool)


def bytes_to_unicode() -> dict[int, str]:
    """The GPT-2 / Hugging Face ByteLevel reversible byte to unicode mapping.

    Printable ranges map to themselves; every other byte is lifted above 0xFF so
    that all 256 have a distinct printable symbol. Codepoints are spelled in hex
    to keep this file ASCII.
    """
    visible = list(range(0x21, 0x7E + 1))  # '!' through '~'
    visible += list(range(0xA1, 0xAC + 1))  # inverted '!' through 'not' sign
    visible += list(range(0xAE, 0xFF + 1))  # registered sign through y umlaut
    bs, cs, extra = visible[:], visible[:], 0
    for byte in range(256):
        if byte not in bs:
            bs.append(byte)
            cs.append(256 + extra)
            extra += 1
    return dict(zip(bs, (chr(codepoint) for codepoint in cs)))


BYTE_SYMBOLS = bytes_to_unicode()  # fixed, so build it once


def read_tokenizer(path: str | Path) -> bytes:
    """Read tokenizer.json, or say what was expected and where."""
    path = Path(path)
    if not path.is_file():
        raise SystemExit(
            f"tokenizer not found: {path}\n"
            f"knots' canonical assets belong in {DEFAULT_TOKENIZER.parent}; "
            f"pass --tokenizer if yours is elsewhere."
        )
    return path.read_bytes()


def check_encoding_contract(config: dict) -> None:
    """Reject any configuration the device encoder does not implement."""
    model = config.get("model") or {}
    if model.get("type") != "BPE":
        raise SystemExit(f"model type is {model.get('type')!r}; the device encoder implements BPE only")
    for field in TOP_LEVEL_ABSENT:
        if config.get(field) is not None:
            raise SystemExit(f"{field} is configured; the device encoder applies none")
    if config.get("added_tokens"):
        raise SystemExit(
            f"{len(config['added_tokens'])} added tokens are configured; the asset carries no table for them"
        )

    pre = config.get("pre_tokenizer")
    if not isinstance(pre, dict) or pre.get("type") != "ByteLevel":
        found = pre.get("type") if isinstance(pre, dict) else pre
        raise SystemExit(f"pre-tokenizer is {found!r}; the device encoder hardcodes ByteLevel")
    for field, required in PRE_TOKENIZER_REQUIRED.items():
        if pre.get(field) is not required:
            raise SystemExit(f"pre-tokenizer {field} is {pre.get(field)!r}, must be {required!r}")

    for field, disabled in MODEL_DISABLED.items():
        if model.get(field) not in disabled:
            raise SystemExit(f"model {field} is {model.get(field)!r}; the device encoder cannot apply it")


def check_vocabulary(vocab: dict[str, int]) -> None:
    """Ids must be a bijection onto 0..len(vocab)-1."""
    non_integer = [(s, i) for s, i in vocab.items() if not is_int(i)]
    if non_integer:
        symbol, value = non_integer[0]
        raise SystemExit(f"vocabulary id for {symbol!r} is {value!r}, not an integer ({len(non_integer)} in total)")

    ids = list(vocab.values())
    if len(set(ids)) != len(ids):
        seen = set()
        for symbol, token_id in vocab.items():
            if token_id in seen:
                raise SystemExit(
                    f"vocabulary id {token_id} is shared by more than one "
                    f"symbol, including {symbol!r}; ids must be unique"
                )
            seen.add(token_id)
    if sorted(ids) != list(range(len(ids))):
        raise SystemExit(
            f"vocabulary ids are not the dense range 0..{len(ids) - 1} "
            f"(found {min(ids)}..{max(ids)}); the asset stores only a count "
            f"and derives merge results from rank, so gaps break both"
        )
    # Dense over a vocabulary this size means every id is below the limit, so no
    # separate per-id bound is needed once the count is checked.
    if len(ids) > UINT16_LIMIT:
        raise SystemExit(f"vocabulary of {len(ids)} does not fit uint16_t token ids")


def merge_pairs(merges: list) -> list[tuple[str, str]]:
    """Normalise merges to (left, right) and reject a repeated pair."""
    pairs, seen = [], {}
    for rank, merge in enumerate(merges):
        left, right = merge.split(" ", 1) if isinstance(merge, str) else merge
        if (left, right) in seen:
            raise SystemExit(
                f"merges {seen[(left, right)]} and {rank} are both "
                f"{left!r} + {right!r}; one pair cannot have two ranks"
            )
        seen[(left, right)] = rank
        pairs.append((left, right))
    return pairs


def build_asset(source: bytes) -> tuple[bytes, int, int, int]:
    """Pack the BTK1 asset from the raw bytes of tokenizer.json.

    Returns (asset_bytes, active_vocab, merge_count, merge_base).
    """
    config = json.loads(source)
    check_encoding_contract(config)

    vocab = config["model"]["vocab"]
    merges = config["model"]["merges"]
    check_vocabulary(vocab)

    byte_token_ids = []
    for byte in range(256):
        symbol = BYTE_SYMBOLS[byte]
        if symbol not in vocab:
            raise SystemExit(
                f"byte symbol {symbol!r} for byte {byte} is missing from the "
                f"vocabulary; a ByteLevel encoder needs all 256"
            )
        byte_token_ids.append(vocab[symbol])

    if not merges:
        raise SystemExit("tokenizer has no merges; nothing to encode with")
    if len(merges) > UINT16_LIMIT:
        raise SystemExit(f"{len(merges)} merges do not fit a uint16_t rank")

    merge_entries = []
    merge_base = None
    for rank, (left, right) in enumerate(merge_pairs(merges)):
        for side, token in (("left", left), ("right", right)):
            if token not in vocab:
                raise SystemExit(f"merge {rank} {side} operand {token!r} is not in the vocabulary")
        joined = left + right
        if joined not in vocab:
            raise SystemExit(f"merge {rank} produces {joined!r}, which is not in the vocabulary")
        result = vocab[joined]
        if merge_base is None:
            merge_base = result
        if result != merge_base + rank:
            raise SystemExit(
                f"merge {rank} produces id {result}, expected "
                f"{merge_base + rank}; the runtime derives the id from the "
                f"rank, so results must be sequential from the base"
            )
        merge_entries.append((vocab[left], vocab[right], rank))

    # The runtime reads a stored base of 0 as "field absent" and substitutes
    # 257, so an asset that meant 0 would be misread.
    if merge_base == 0:
        raise SystemExit("merge base is 0, which the runtime cannot distinguish from an asset that predates the field")

    merge_entries.sort(key=lambda entry: (entry[0] << 16) | entry[1])

    packed = bytearray()
    packed.extend(
        struct.pack(
            HEADER_STRUCT,
            MAGIC,
            FORMAT_VERSION,
            len(vocab),
            len(merge_entries),
            RESERVED,
            merge_base,
            hashlib.sha256(source).digest()[:28],
        )
    )
    packed.extend(struct.pack("<256H", *byte_token_ids))
    for left, right, rank in merge_entries:
        packed.extend(struct.pack("<IH", (left << 16) | right, rank))

    expected = struct.calcsize(HEADER_STRUCT) + 512 + 6 * len(merge_entries)
    if len(packed) != expected:
        raise SystemExit(f"packed {len(packed)} bytes, layout requires {expected}")
    return bytes(packed), len(vocab), len(merge_entries), merge_base


def render(asset: bytes) -> str:
    """Render generated/tokenizer_encoder.h: the BTK1 asset as a PROGMEM byte array."""
    lines = [
        BANNER,
        "// BTK1 encoder tables for runtime/bpe_tokenizer.h.",
        "#ifndef TOKENIZER_ENCODER_H",
        "#define TOKENIZER_ENCODER_H",
        # Defined by the Arduino core, absent on a host compiler, and this
        # header is included by both.
        "#ifndef PROGMEM",
        "#define PROGMEM",
        "#endif",
        f"static const unsigned char TOKENIZER_ENCODER_ASSET[{len(asset)}] PROGMEM = {{",
    ]
    for i in range(0, len(asset), BYTES_PER_LINE):
        lines.append("  " + ",".join(str(b) for b in asset[i : i + BYTES_PER_LINE]) + ",")
    lines += [
        "};",
        f"#define TOKENIZER_ENCODER_ASSET_SIZE {len(asset)}",
        "#endif",
    ]
    return "\n".join(lines) + "\n"


def generate(tokenizer_path: str | Path, out_path: str | Path, asset_path: str | Path | None = None) -> Path:
    """Validate the tokenizer and write the header. Returns the path.

    asset_path additionally writes the raw BTK1 bytes, which is what the host
    conformance check loads: it reads the asset from a file rather than being
    recompiled against a header for every tokenizer.
    """
    source = read_tokenizer(tokenizer_path)
    asset, active_vocab, merge_count, merge_base = build_asset(source)

    out_path = Path(out_path)
    # Generated headers are ignored, so the directory is absent in a fresh clone.
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render(asset))

    print(
        f"wrote {out_path}: {len(asset)} B asset, vocab {active_vocab}, {merge_count} merges, merge base {merge_base}"
    )
    if asset_path is not None:
        asset_path = Path(asset_path)
        asset_path.parent.mkdir(parents=True, exist_ok=True)
        asset_path.write_bytes(asset)
        print(f"wrote {asset_path}: {len(asset)} B raw BTK1")
    print(f"  tokenizer sha256 {hashlib.sha256(source).hexdigest()}")
    return out_path


def main() -> None:
    """Parse --tokenizer/--out/--asset, then generate the encoder header."""
    ap = argparse.ArgumentParser(description="Pack the knots BPE encoder tables into a C header.")
    ap.add_argument("--tokenizer", default=DEFAULT_TOKENIZER, help="canonical tokenizer.json the asset is built from")
    ap.add_argument("--out", default=DEFAULT_OUT, help="header to write")
    ap.add_argument("--asset", default=None, help="also write the raw BTK1 bytes here, for host checks")
    args = ap.parse_args()
    generate(args.tokenizer, args.out, args.asset)


if __name__ == "__main__":
    main()
